#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         3
bspc config focused_border_color \#FFFFB3
bspc config normal_border_color \#1A1100
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#AutoStart
picom & #compositor
feh --bg-fill ~/.config/wallpaper/japan_cherry_blossom.jpg #wallpaper
$HOME/.config/polybar/launch.sh #bar
